version: '3.3'
services:
  rancher:
    image: rancher/rancher:latest
    restart: always
    container_name: rancher
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/app/rancher/:/var/lib/rancher
